project: 
  type: website
  
website: 
  page-navigation: true
  title: ianalexmac.github.io 
  site-url: https://ianalexmac.github.io/ 
  repo-url: https://github.com/ianalexmac/ianalexmac.github.io
  repo-actions: [issue]
  
  page-footer:
    right: "This page is based on Openscape's [Quarto Site Template](https://github.com/Openscapes/quarto-website-tutorial) and built with [Quarto](https://quarto.org/) ."
    left: "&copy; CC-By , 2023"
    
  sidebar:
    logo: "images/data-duck.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/ianalexmac.github.io
        text: "ianalexmac's GitHub"      

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
        icon: dot
      - href: sandbox.qmd
        text: Sandbox
        icon: dot
      - href: wrangle.qmd
        text: Wrangle
        icon: dot
      - href: slides/presentation_demo.qmd
        text: Example Presentation
        icon: dot



format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true


filters:
  - quarto

  
